stages:
  - test
  - build

backend-test:
  stage: test
  image: python:3.11
  before_script:
    - cd backend
    - pip install --upgrade pip
    - pip install -r requirements.txt
  script:
    - python -m unittest discover -s test -p "*_test.py"

frontend-build:
  stage: build
  image: node:20
  before_script:
    - cd Frontend
    - npm install
  script:
    - npm run build
  artifacts:
    paths:
      - Frontend/dist/
  cache:
    paths:
      - Frontend/node_modules/