// Grouped by section to match the menu layout

export const MENU_DATA = {
  Starters: [
    {
      id: 1,
      name: "Guacamole & Chips",
      description: "Hand-mashed avocado, jalapeño, lime zest & Oaxacan pink salt.",
      price: "£7.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "350 kcal",
    },
    {
      id: 2,
      name: "Tlayuda Tostada",
      description: "Crispy corn base, black bean, quesillo, chorizo & fresh avocado.",
      price: "£9.00",
      dietary: ["Gluten-Free"],
      allergens: ["Milk", "Soy"],
      calories: "500 kcal",
    },
    {
      id: 3,
      name: "Ceviche Verde",
      description: "Sea bass, tomatillo, cucumber, coriander & tiger's milk.",
      price: "£12.00",
      dietary: ["Gluten-Free"],
      allergens: ["Fish"],
      calories: "180 kcal",
    },
    {
      id: 4,
      name: "Elote Esquites",
      description: "Charred corn, crema, cotija cheese, ancho chilli & epazote.",
      price: "£8.00",
      dietary: ["Vegetarian", "Gluten-Free"],
      allergens: ["Milk"],
      calories: "250 kcal",
    },
  ],
  Mains: [
    {
      id: 5,
      name: "Mole Negro Chicken",
      description: "Free-range thigh braised in a 30-ingredient black mole, sesame rice.",
      price: "£18.00",
      dietary: [],
      allergens: ["Soy", "Nuts"],
      calories: "600 kcal",
    },
    {
      id: 6,
      name: "Barbacoa Tacos",
      description: "Slow-braised beef cheek, white onion, coriander & salsa roja. Three pieces.",
      price: "£16.00",
      dietary: [],
      allergens: [],
      calories: "300 kcal (per taco)",
    },
    {
      id: 7,
      name: "Portobello Enchiladas",
      description: "Roasted mushrooms, black bean, chipotle sauce & cashew crema.",
      price: "£14.00",
      dietary: ["Vegan"],
      allergens: [],
      calories: "400 kcal",
    },
    {
      id: 8,
      name: "Snapper Veracruz",
      description: "Pan-seared whole snapper, olives, capers & fresh tomato broth.",
      price: "£22.00",
      dietary: ["Gluten-Free"],
      allergens: ["Fish"],
      calories: "450 kcal",
    },
  ],
  Dessert: [
    {
      id: 9,
      name: "Churro Sundae",
      description: "Crispy churros, vanilla bean ice cream & dark chocolate mole sauce.",
      price: "£8.00",
      dietary: ["Vegetarian"],
      allergens: ["Milk", "Gluten", "Eggs"],
      calories: "550 kcal",
    },
    {
      id: 10,
      name: "Mezcal Flan",
      description: "Silky caramel custard with a smoky mezcal caramel drizzle.",
      price: "£7.00",
      dietary: ["Vegetarian", "Gluten-Free"],
      allergens: ["Milk", "Eggs"],
      calories: "320 kcal",
    },
    {
      id: 11,
      name: "Mango Sorbet",
      description: "Alphonso mango, chilli salt & fresh lime. Completely dairy free.",
      price: "£6.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "120 kcal",
    },
  ],
  Sides: [
    {
      id: 12,
      name: "Black Bean Pot",
      description: "Slow-cooked with avocado leaf, epazote & lime crema.",
      price: "£4.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "200 kcal",
    },
    {
      id: 13,
      name: "Corn Tortillas",
      description: "Fresh nixtamal masa, made in-house daily. Four pieces.",
      price: "£3.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "60 kcal (per tortilla)",
    },
    {
      id: 14,
      name: "Pickled Jalapeños",
      description: "House-pickled chillies, carrots & white onion in apple cider vinegar.",
      price: "£3.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "5 kcal (per tbsp)",
    },
    {
      id: 15,
      name: "Mexican Rice",
      description: "Tomato-braised rice with cumin, garlic & fresh coriander.",
      price: "£4.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "200 kcal",
    },
  ],
  Drinks: [
    {
      id: 16,
      name: "Hibiscus Agua Fresca",
      description: "House-dried hibiscus, lime, cane sugar & still water.",
      price: "£4.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "70 kcal (per cup)",
    },
    {
      id: 17,
      name: "Mezcal Margarita",
      description: "Joven mezcal, fresh lime juice, agave syrup & smoked salt rim.",
      price: "£11.00",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: [],
      calories: "250 kcal",
    },
    {
      id: 18,
      name: "Horchata",
      description: "Rice milk, cinnamon, vanilla & a hint of almond. Served chilled.",
      price: "£4.50",
      dietary: ["Vegan", "Gluten-Free"],
      allergens: ["Nuts"],
      calories: "150 kcal (per cup)",
    },
    {
      id: 19,
      name: "Mexican Lager",
      description: "Ice-cold bottle served with lime. Ask your server for today's selection.",
      price: "£5.00",
      dietary: [],
      allergens: [],
      calories: "150 kcal (per 12 oz bottle)",
    },
    {
      id: 20,
      name: "Water",
      description: "Ice-cold and refreshing. Ask your server for alternative temperatures.",
      price: "£2.50",
      dietary: [],
      allergens: [],
      calories: "0 kcal",
    },
  ],
};